### ISSUE TITLE
Add IPA for overall recognition syllables (整体认读音节) in README?

### ISSUE THREAD

**Issue by ayaka14732** [NGLI/rime-wugniu_soutseu#1]
Thanks for this project! Currently there are IPA for 聲母 and 韻母 in the README. But according to the [instructional video](https://www.bilibili.com/video/BV16x411B71T?p=4), there are also 14 整体认读音节. Would it be better to add them to the README as well?

**Comment by shinzoqchiuq** [comment]
Thanks for the issue.

The video you mentioned is made for beginners, some syllables which are difficult to break down into initials and finals are teached as the overall recognition syllables. Here mentioned in [lesson 9](https://www.bilibili.com/video/BV16x411B71T?p=10), the overall recognition syllabary *pu* is actually *p* + *u*. So do the other overall recognition syllables. As a result, I did not mention them in README. Just like the appendix of *Xinhua Dictionary*, which did not mention the overall recognition syllables of mandarin too.

**Comment by ayaka14732** [comment]
Thank you for this clear explanation!
